"""Harness installer — writes agent instruction files.

``install_agent_file`` renders a ``.github/agents/zhar.agent.md`` (or any
target path) from a combination of:

- A project memory snapshot (via ``export_text``)
- Project facts (key-value flags from ``Facts``)

The file is designed to be consumed by AI agents as a system prompt addition
that gives them live project context without manual maintenance.
"""
from __future__ import annotations

from pathlib import Path

from zhar.mem.export import export_text
from zhar.mem.store import MemStore
from zhar.utils.facts import Facts

_HEADER = """\
<!-- This file is auto-generated by zhar. Do not edit by hand.
     Regenerate with: zhar install -->

# zhar agent context

This file provides persistent project memory to AI agents working in this
repository.  It is generated from `.zhar/mem/` and `.zhar/facts.json`.

---
"""


def install_agent_file(
    store: MemStore,
    facts: Facts | None,
    output: Path,
) -> Path:
    """Render and write the agent instruction file to *output*.

    Parameters
    ----------
    store:
        The MemStore to export memory from.
    facts:
        Optional Facts instance.  When provided, a facts section is prepended.
    output:
        Destination path (typically ``.github/agents/zhar.agent.md``).

    Returns
    -------
    Path
        The path the file was written to.
    """
    output.parent.mkdir(parents=True, exist_ok=True)

    sections: list[str] = [_HEADER]

    if facts:
        all_facts = facts.all()
        if all_facts:
            lines = ["## Project facts\n"]
            for k, v in sorted(all_facts.items()):
                lines.append(f"- **{k}**: {v}")
            sections.append("\n".join(lines) + "\n")

    snapshot = export_text(store)
    sections.append("## Memory snapshot\n\n" + snapshot)

    output.write_text("\n\n".join(sections), encoding="utf-8")
    return output


def uninstall_agent_file(output: Path) -> bool:
    """Remove the agent file at *output*.

    Returns True if the file existed and was removed, False otherwise.
    """
    if output.exists():
        output.unlink()
        return True
    return False
