"""Harness installer helpers for mirrored files and generated memory-context output.

``install_agent_file`` renders a generated context file (typically
``.github/agents/zhar-context.agent.md``) from a combination of:
any target path) from a combination of:

- A project memory snapshot (via ``export_text``)
- Project facts (key-value flags from ``Facts``)

The file is designed to be consumed by AI agents as a system prompt addition
that gives them live project context without manual maintenance.
"""
from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from zhar.harness.getter import HarnessEntry
from zhar.harness.paths import default_context_output_path
from zhar.harness.paths import default_harness_install_path
from zhar.mem.export import export_text
from zhar.mem.store import MemStore
from zhar.utils.facts import Facts

_HEADER = """\
<!-- This file is auto-generated by zhar. Do not edit by hand.
    Regenerate with: uv run zhar install
    Or: uv run zhar harness export-mem-context -->

# zhar agent context

This file provides persistent project memory to AI agents working in this
repository.  It is generated from `.zhar/mem/` and the effective zhar facts
set (global facts plus project facts, with project values taking precedence).

---
"""


def _facts_mapping(facts: Facts | Mapping[str, str] | None) -> dict[str, str]:
    """Normalize supported facts inputs to a plain dictionary."""
    if facts is None:
        return {}
    if isinstance(facts, Facts):
        return facts.all()
    return dict(facts)


def install_agent_file(
    # %ZHAR:530d%
    store: MemStore,
    facts: Facts | Mapping[str, str] | None,
    output: Path,
) -> Path:
    """Render and write the agent instruction file to *output*.

    Parameters
    ----------
    store:
        The MemStore to export memory from.
    facts:
        Optional Facts instance.  When provided, a facts section is prepended.
    output:
        Destination path (typically ``.github/agents/zhar.agent.md``).

    Returns
    -------
    Path
        The path the file was written to.
    """
    output.parent.mkdir(parents=True, exist_ok=True)

    sections: list[str] = [_HEADER]

    all_facts = _facts_mapping(facts)
    if all_facts:
        lines = ["## Effective facts\n"]
        for k, v in sorted(all_facts.items()):
            lines.append(f"- **{k}**: {v}")
        sections.append("\n".join(lines) + "\n")

    snapshot = export_text(
        store,
        include_runtime_context=True,
        project_root=store.project_root,
    )
    sections.append("## Memory snapshot\n\n" + snapshot)

    output.write_text("\n\n".join(sections), encoding="utf-8")
    return output


def export_mem_context_file(
    store: MemStore,
    facts: Facts | Mapping[str, str] | None,
    output: Path | None = None,
) -> Path:
    """Write the generated legacy memory-context file to *output*."""
    target = output if output is not None else default_context_output_path()
    return install_agent_file(store, facts, target)


def install_harness_entry(entry: HarnessEntry, output: Path | None = None) -> Path:
    """Write a mirrored harness entry to its default or requested workspace path."""
    target = output if output is not None else default_harness_install_path(entry.kind, entry.path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(entry.path.read_text(encoding="utf-8"), encoding="utf-8")
    return target


def install_context_file(
    store: MemStore,
    facts: Facts | Mapping[str, str] | None,
    output: Path | None = None,
) -> Path:
    """Compatibility alias for exporting the legacy memory-context file."""
    return export_mem_context_file(store, facts, output)


def uninstall_agent_file(output: Path) -> bool:
    """Remove the agent file at *output*.

    Returns True if the file existed and was removed, False otherwise.
    """
    if output.exists():
        output.unlink()
        return True
    return False
