"""Agent installer — write generated agent instruction files from project state."""

from __future__ import annotations

from pathlib import Path

from zhar.mem.export import export_text
from zhar.mem.store import MemStore
from zhar.utils.facts import Facts

_HEADER = """\
<!-- This file is auto-generated by zhar. Do not edit by hand.
     Regenerate with: zhar install -->

# zhar agent context

This file provides persistent project memory to AI agents working in this
repository.  It is generated from `.zhar/mem/` and `.zhar/facts.json`.

---
"""


def install_agent_file(
    # %ZHAR:530d%
    store: MemStore,
    facts: Facts | None,
    output: Path,
) -> Path:
    """Render and write the agent instruction file to *output*."""
    output.parent.mkdir(parents=True, exist_ok=True)

    sections: list[str] = [_HEADER]
    if facts:
        all_facts = facts.all()
        if all_facts:
            lines = ["## Project facts\n"]
            for key, value in sorted(all_facts.items()):
                lines.append(f"- **{key}**: {value}")
            sections.append("\n".join(lines) + "\n")

    snapshot = export_text(
        store,
        include_runtime_context=True,
        project_root=store.project_root,
    )
    sections.append("## Memory snapshot\n\n" + snapshot)

    output.write_text("\n\n".join(sections), encoding="utf-8")
    return output


def uninstall_agent_file(output: Path) -> bool:
    """Remove the generated agent file at *output* if it exists."""
    if output.exists():
        output.unlink()
        return True
    return False